# prettier-ignore

org: ${file(./config.yml):aws.org}
service: bonzai-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${file(./config.yml):aws.role}

functions:
  createBooking:
    handler: functions/Bookings/index.handler
    events:
      - httpApi:
          path: /api/bookings
          method: POST

  getRooms:
    handler: functions/GetRooms/index.handler
    events:
      - httpApi:
          path: /api/rooms
          method: GET
  
  getRoomsByType:
    handler: functions/GetRoomByType/index.handler
    events:
      - httpApi:
          path: /api/rooms/{type}
          method: GET

  getBookingById:
    handler: functions/GetBookingsById/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: GET

  removeBooking:
    handler: functions/RemoveBooking/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: DELETE

  changeBooking:
    handler: functions/ChangeBooking/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: PUT

resources:
  Resources:
    RoomTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RoomTypes
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookings
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
