# prettier-ignore

org: ${file(./config.yml):aws.org}
service: bonz.ai-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${file(./config.yml):aws.role}

functions:
  handler:
    handler: Bookings/index.handler
    events:
      - httpApi:
          path: /api/bookings
          method: POST

  handler:
    handler: GetRooms/index.handler
    events:
      - httpApi:
          path: /api/rooms
          method: GET
  
  handler:
    handler: GetRoomByType/index.handler
    events:
      - httpApi:
          path: /api/rooms/{type}
          method: GET

  handler:
    handler: GetBookingsById/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: GET

  handler:
    handler: RemoveBooking/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: DELETE

  handler:
    handler: ChangeBooking/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: PUT

resources:
  Resources:
    RoomTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RoomTypes
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: SK
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookings
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: RoomTypeIndex
          KeySchema:
          - AttributeName: roomType
            KeyType: HASH
          Projection:
            ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    
    
